---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crdtry.kubebuilder.test
  resources:
  - lpxpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crdtry.kubebuilder.test
  resources:
  - lpxpods/finalizers
  verbs:
  - update
- apiGroups:
  - crdtry.kubebuilder.test
  resources:
  - lpxpods/status
  verbs:
  - get
  - patch
  - update
