apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lpxpod-server-cluster-role
rules:
- apiGroups:
  - crdtry.kubebuilder.test
  resources:
  - lpxpod
  verbs:
  - create
  - get
  - delete
  - list
  - watch